name: Backend CI

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checks directory
        run: |
          pwd
          ls
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Verify application imports
        run: python -c "import main"

      - name: Build Docker image
        run: docker build -t chipin-api .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: |
          curl -v \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
            https://deploy.gyozas.dev/deploy

  notify:
    needs:
      - build
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        if: always()
        run: |
          JOB_STATUS=""
          
          JOB_STATUS+="Build: "
          if [ "${{ needs.build.result }}" = "success" ]; then JOB_STATUS+="SUCCESS"
          else JOB_STATUS+="FAILED"
          fi
          JOB_STATUS+=$'\n'
          
          JOB_STATUS+="Deploy: "
          if [ "${{ needs.deploy.result }}" = "success" ]; then JOB_STATUS+="SUCCESS"
          else JOB_STATUS+="FAILED"
          fi
          
          MESSAGE="
          Deployment Pipeline $STATUS
          
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.event.head_commit.message }}
          Run: #${{ github.run_number }}
          
          $JOB_STATUS
          
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          curl -v \
          -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\":\"${{ secrets.TELEGRAM_CHAT_ID }}\",
            \"text\":\"$MESSAGE\"
          }"
